config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'users#home'


  resources :users, except: [:new]
  resources :companies, only: [:index, :show]
  resources :systems, only: [:index, :show]

  resources :games, only: [:index, :show, :new, :create] do 
    resources :events, only: [:index, :new, :create, :show]
  end 

  resources :events
  resources :user_games, only: [:edit]

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  get '/delete' => 'users#delete_page'
  delete '/delete' => 'users#delete'

  get '/add_game/:id' => 'user_games#add_game', as: "add_game"
  get '/delete_game/:id' => 'user_games#delete_game', as: "delete_game"
  patch '/add_rating/:id' =>  'user_games#add_rating', as: "add_rating"
   
  get '/add_event/:id' => 'user_events#add_event', as: "add_event"
  get '/delete_event/:id' => 'user_events#delete_event', as: "delete_event"

  get '/rating/:rating' => 'games#rating', as: "rating"

  get '/auth/github/callback', to: 'users#create'


end

app/models/user.rb
class User < ApplicationRecord
    validates(:username, :presence => true, :uniqueness => true)
    validates(:email, :presence => true, :uniqueness => true)
    validates(:password, :presence => true)
    has_secure_password

    has_many :user_games 
    has_many :games, through: :user_games 

    has_many :user_events
    has_many :events, through: :user_events 

    has_many :hosting_events, class_name: "Event", foreign_key: :host_id
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_login, only: [:show, :edit, :update, :delete_page, :delete]

    def home 

    end 

    def new 
        @user = User.new
    end 

    def create 
        if params[:user]
             @user = User.new(user_params)
                if 
                    @user.valid?
                    @user.save
                    session[:user_id] = @user.id 
                    redirect_to user_path(@user)
                else 
                    render :new 
                end 
        else 
            @user = User.find_or_create_by(uid: auth['uid']) do |u|
                u.name = auth['info']['name']
                u.email = auth['info']['email']
                u.image = auth['info']['image']
            end 
            session[:user_id] = @user.id 
            redirect_to user_path(@user)
        end
    end 

    def show 
        @user = User.find(session[:user_id])
    end

    def edit 
        @user = current_user
        redirect_to login_path unless logged_in?
    end 

    def update 
        @user = current_user
        @user.username = params[:user][:username]
        @user.email = params[:user][:email]
        @user.password = params[:user][:password]
            if @user.valid? 
               @user.save 
               redirect_to user_path(@user)
            else 
                render :edit
            end 
    end 

    def delete_page 
        @user = current_user
    end 

    def delete
        @user = current_user 
        @user.delete
        redirect_to '/'
    end 
    
    private 

    def user_params 
        params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end 

    def require_login
        unless logged_in?
            flash[:error] = "You must be logged in to access this section"
            redirect_to login_path 
          end
    end

    def auth
        request.env['omniauth.auth']
    end

    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<% if @user.errors.any? %>
   <div id="error_explanation">
      <h2> 
         <%= pluralize(@user.errors.count, "error") %>
         prohibited this user from being saved:
      </h2>

      <ul> 
        <% @user.errors.full_messages.each do |msg| %>
            <li> <%= msg %> </li>
        <% end %>
     </ul>
    </div>
    <% end %>

<%= form_for(@user) do |f| %>
    <b>Username:</b> <%= f.text_field :username %></br>
    <b>Email:</b> <%= f.text_field :email %></br>
    <b>Password:</b> <%= f.password_field :password %></br>
    <b>Confirm Password:</b> <%= f.password_field :password_confirmation %></br>
    <%= f.submit %>
    <% end %> 

app/views/users/delete_page.html.erb
<h1> Delete your Account </h1>
<br>
<br>
<h4 class="warning">WARNING: Deleting your account will completely remove it from the database. 
         This action cannot be undone.</h4>
<br>
<%= form_tag(delete_path, method: :delete) do %>
  <%= submit_tag "Delete Account" %>
<% end %>

app/views/users/edit.html.erb
<h1> Update your Account Information </h1>

<%= render 'form' %>
</br>
<div class="delete_account"><%= link_to "Delete your Account", delete_path %></div>

app/views/users/home.html.erb
<h1> Welcome to Vie Games!</h1>
<% if current_user %>
<div class="motto"<h3><i> The premier app for competitive gamers.</i></h3></div></br>

<h5>Here at <b>Vie Games</b>, our users don't just play games for fun, they play games to win.</h5>

    <li>• Search your favorite games in our database and see their upcoming events.</li>
    <li>• Compete against other players to win prizes and bragging rights.</li>
    <li>• Don't see the game or event you're looking for? No problem. Just add it to the database or create an event yourself.</li>
    


<% else %>
Please <%= link_to "Sign Up", signup_path %>  or <%= link_to "Log In", login_path %> to continue.
<% end %>

app/views/users/new.html.erb
<h1> Create an Account for Vie Games! </h1>

<%= render 'form' %>


<%= link_to "Sign Up with your Github Account", '/auth/github' %>

app/views/users/show.html.erb
<h1> Welcome <%= current_user.username %> ! </h1>

<h2><b> Here is your list of Games!</b></h2>
    
<h3> <b>Nintendo Switch</b></h3>
    
    <% if current_user.games.none? {|game| game.system.name == "Nintendo Switch"} %>
        <%= "You don't own any Switch titles!" %>
    <% elsif %>
        <% current_user.games.each do |game| %>
            <% if game.system.name == "Nintendo Switch" %>
                <li> <%= link_to game.title, game_path(game) %>  </li>
            <% end %>
        <% end %>
    <% end %>

    <h3> <b>Nintendo 3DS </b></h3>

    <% if current_user.games.none? {|game| game.system.name == "Nintendo 3DS"} %>
        <%= "You don't own any 3DS titles!" %>
    <% elsif %>
        <% current_user.games.each do |game| %>
            <% if game.system.name == "Nintendo 3DS" %>
                <li> <%= link_to game.title, game_path(game) %> </li>
            <% end %>
        <% end %>
    <% end %>

    <h3><b> Xbox One </b></h3>

    <% if current_user.games.none? {|game| game.system.name == "Xbox One"} %>
        <%= "You don't own any Xbox One titles!" %>
    <% elsif %>
        <% current_user.games.each do |game| %>
            <% if game.system.name == "Xbox One" %>
                <li> <%= link_to game.title, game_path(game) %> </li>
            <% end %>
        <% end %>
    <% end %>

    <h3> <b>Playstation 4 </b></h3>

    <% if current_user.games.none? {|game| game.system.name == "Playstation 4"} %>
        <%= "You don't own any Playstation 4 titles!" %>
    <% elsif %>
        <% current_user.games.each do |game| %>
            <% if game.system.name == "Playstation 4" %>
             <li> <%= link_to game.title, game_path(game) %> </li>
            <% end %>
        <% end %>
    <% end %> <br> <br>

    <h3> <b>Your Upcoming Gaming Events</b> </h3>
            <% current_user.events.each do |event| %>
                <% if event.upcoming %>
                <li> <i><%= event.date_time %></i>
               <%= link_to event.game.title, event_path(event)%> </li>
               <% end %>
               <% end %></br></br>
