config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'users#home'


  resources :users, except: [:new]
  resources :companies, only: [:index, :show]
  resources :systems, only: [:index, :show]

  resources :games, only: [:index, :show, :new, :create] do 
    resources :events, only: [:index, :new, :create, :show]
  end 

  resources :events
  resources :user_games, only: [:edit]

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  get '/delete' => 'users#delete_page'
  delete '/delete' => 'users#delete'

  get '/add_game/:id' => 'user_games#add_game', as: "add_game"
  get '/delete_game/:id' => 'user_games#delete_game', as: "delete_game"
  patch '/add_rating/:id' =>  'user_games#add_rating', as: "add_rating"
   
  get '/add_event/:id' => 'user_events#add_event', as: "add_event"
  get '/delete_event/:id' => 'user_events#delete_event', as: "delete_event"

  get '/rating/:rating' => 'games#rating', as: "rating"

  get '/auth/github/callback', to: 'users#create'


end

app/models/event.rb
class Event < ApplicationRecord
    scope :online, -> { where(location: "Online") }
    scope :in_person, -> { where(location: "In Person")}

    belongs_to :game 
    has_many :user_events 
    has_many :users, through: :user_events
    belongs_to :host, class_name: "User", optional: true

    validate :event_date_cannot_be_in_the_past
    
    validates(:max_num_entrants, numericality: {
        only_integer: true,
        greater_than_or_equal_to: 3
      }
    )
    validates(:entrance_fee, numericality: {
        only_integer: true,
        greater_than_or_equal_to: 0
      }
    )
    validates(:prize,  numericality: {
        only_integer: true,
        greater_than_or_equal_to: 0
      }
    )
    validates(:game_id, :presence => true)
    validates :game_id, uniqueness: {
        scope: %i[date],
        message: 'has already been created for this date.'
    }
    
    validates(:location, :presence => true)

 

    def event_date_cannot_be_in_the_past
        if date.present? && date < Date.today
          errors.add(:date, "can't be in the past")
        end
    end    

    def date_time
        self.date.strftime('%B %d, %Y')
    end

    def status 
        if self.users.count < self.max_num_entrants 
            return "Open"
        else 
            return "Closed"
        end 
    end 

    def upcoming
        self.date >= Date.today 
    end 

   def host_username
        self.host.username
   end
    
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    before_action :require_login
    before_action :find_event, only: [:show, :edit, :update, :delete]

    def index
        if !params[:game_id]
           @events = Event.all 
        else 
            @game_id = params[:game_id].to_i
            @game = Game.find(params[:game_id])
            @events = Event.all.select {|event|event.game_id == @game_id}
            render :game_event_index
        end 
    end 

    def new
        @event = Event.new
        if params[:game_id]
            @game_id = params[:game_id]
        else
            @games = Game.all
        end
    end 

    def create
        @event = Event.new(event_params)
        
        if @event.valid?
            if @event.host_id == 1 
               @event.host_id = current_user.id 
            elsif @event.host_id == 0
                @event.host_id = nil 
            end 
            @event.save 
            user_event = UserEvent.create(user_id: current_user.id, event_id: @event.id)
            if current_user.games.find{|game| game.id == @event.game_id}
                redirect_to event_path(@event)
            else
                user_game = UserGame.create(user_id: current_user.id, game_id: @event.game_id)
                redirect_to event_path(@event) 
            end 
        else 
            render :new 
        end 
    end 

    def show
    end 

    def edit 
        render :access_denied unless @event.host == true 
    end 

    def update
        @event.date = params[:event][:date]
        @event.location = params[:event][:location]
        @event.entrance_fee = params[:event][:entrance_fee]
        @event.prize = params[:event][:prize]
        @event.max_num_entrants = params[:event][:max_num_entrants]
        @event.host_id = params[:event][:host_id]
        @event.game_id = params[:event][:game_id]
            
        if @event.valid?
            @event.save
            redirect_to event_path(@event)
        else 
            render :edit
        end 
     end 

    def delete
        if @event.host 
           @event.delete
           redirect_to events_path
        else 
            render :access_denied
        end 
    end 

    private 

    def event_params 
        params.require(:event).permit(:date, :location, :entrance_fee, :prize, :host_id, :max_num_entrants, :game_id)
    end 

    def require_login
        unless logged_in?
            flash[:error] = "You must be logged in to access this section"
            redirect_to login_path 
          end
    end

    def find_event 
        @event = Event.find(params[:id])
    end 
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/access_denied.html.erb
<h1> Access Denied </h1>

<h4> Only the host may edit or delete the event </h4>

<%= link_to "Return Home", user_path(current_user) %>

app/views/events/edit.html.erb
<h1>Edit the <%=@event.game.title%> Event</h1>

<%= form_for(@event) do |f| %> 
    <% if @game_id %>
        <%= f.hidden_field(:game_id, value: @game_id) %>
    <% else %>
        <%= f.collection_select(:game_id, Game.all, :id, :title) %>
    <% end %> <br>
    When: <%= f.date_field :date %><br>
    Number of Entrants: <%= f.number_field :max_num_entrants %><br>
    Entrance Fee: <%= f.number_field :entrance_fee %><br>
    Prize: <%= f.number_field :prize %><br>
    Location: Online: <%= f.radio_button(:location, "Online")%>
              In Person: <%= f.radio_button(:location, "In Person")%><br>
    <%= f.label "Host?" %>
    <%= f.check_box :host %> <br />
    <%= f.submit "Edit Event" %>
    <% end %>

app/views/events/game_event_index.html.erb
<h1>Upcoming <%=@game.title %> Events </h1>

<h3> <b>Online</b> </h3>
<% if @events.none? {|event| event.location == "Online"} %>
    <%= "There are no Online events for #{@game.title}." %>
<% elsif %>
<% @events.each do |event| %>
    <% if event.location == "Online"%>
        <li><%= link_to event.date_time, event_path(event) %> </li>
    <% end %>
<% end %>
<% end %>
    

<h3> <b>In Person</b></h3>
<% if @events.none? {|event| event.location == "In Person"} %>
    <%= "There are no In Person events for #{@game.title}." %>
<% elsif %>

<% @events.each do |event| %>
    <% if event.location == "In Person"%>
       <li> <%= link_to event.date_time, event_path(event) %> </li>
    <% end %>
<% end %>
<% end %>

app/views/events/index.html.erb
<h1> Upcoming Events </h1>

<h3> <b>Online Events </b></h3>
    <% Event.online.each do |event| %>
        <% if event.upcoming %>
        <li> <%= event.date_time %>
        <%= link_to event.game.title, event_path(event) %></li>
        <% end %>
        <% end %>


<h3><b> In Person Events</b> </h3>
<% Event.in_person.each do |event| %>
    <% if event.upcoming %>
    <li> <%= event.date_time %>
    <%= link_to event.game.title, event_path(event) %></li>
    <% end %>
    <% end %>
<br>
<br>
<h5><div class="create_event"><%= link_to "Create an Event", new_event_path %></h5></div>

app/views/events/new.html.erb
<% if @event.errors.any? %>
   <div id="error_explanation">
      <h2> 
         <%= pluralize(@event.errors.count, "error") %>
         prohibited this event from being saved:
      </h2>

      <ul> 
        <% @event.errors.full_messages.each do |msg| %>
            <li> <%= msg %> </li>
        <% end %>
     </ul>
    </div>
    <% end %>


<h1> Create an Event </h1><br>

<%= form_for(@event) do |f| %> 
    <% if @game_id %>
        <%= f.hidden_field(:game_id, value: @game_id) %>
    <% else %>
       <b>Game:</b> <%= f.collection_select(:game_id, Game.all, :id, :title) %>
    <% end %> <br>
    <b>When:</b> <%= f.date_field :date %><br>
    <b>Number of Entrants:</b> <%= f.number_field :max_num_entrants %><br>
    <b>Entrance Fee:</b> <%= f.number_field :entrance_fee %><br>
    <b>Prize:</b> <%= f.number_field :prize %><br>
    <b>Location:</b> Online: <%= f.radio_button(:location, "Online")%>
              In Person: <%= f.radio_button(:location, "In Person")%><br>
    <b><%= f.label "Host?" %></b>
    <%= f.check_box :host_id %> <br />
    <%= f.submit "Create Event" %>
    <% end %>
  


app/views/events/show.html.erb
<h1> <%= link_to @event.game.title, game_path(@event.game) %> Tournament </h1>

<b>When:</b><%= @event.date_time %></br></br>    
<b>Location:</b> <%= @event.location %></br></br>
<b>Maximum Number of Entrants:</b> <%= @event.max_num_entrants %></br></br>
<b>Number of Participants:</b> <%= @event.users.count %></br></br>
<b>Entrance Fee:</b> $<%= @event.entrance_fee %></br></br>
<b>Prize Money: </b> $<%= @event.prize %></br></br>
<b>Status: </b> <%= @event.status %> </br></br>
<% if @event.host %>
<b>Hosted by:</b><%= @event.host_username %></br></br>
<% end %>



<% if current_user.events.find{|event| event.id == @event.id} %>
    <%= link_to "Remove this Tournament from your Events", delete_event_path(@event)%><br>
<% elsif !current_user.events.find{|event| event.id == @event.id} && @event.status == "Open"%>
    <%= link_to "Join this Tournament", add_event_path(@event) %><br>
<% end %> 

<% if @event.host_id == current_user.id %>
<%= link_to "Edit this Event", edit_event_path(@event)%>
<% end %></br>

<%= link_to "Upcoming Events", events_path %></br></br>
