config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'users#home'


  resources :users, except: [:new]
  resources :companies, only: [:index, :show]
  resources :systems, only: [:index, :show]

  resources :games, only: [:index, :show, :new, :create] do 
    resources :events, only: [:index, :new, :create, :show]
  end 

  resources :events
  resources :user_games, only: [:edit]

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  get '/delete' => 'users#delete_page'
  delete '/delete' => 'users#delete'

  get '/add_game/:id' => 'user_games#add_game', as: "add_game"
  get '/delete_game/:id' => 'user_games#delete_game', as: "delete_game"
  patch '/add_rating/:id' =>  'user_games#add_rating', as: "add_rating"
   
  get '/add_event/:id' => 'user_events#add_event', as: "add_event"
  get '/delete_event/:id' => 'user_events#delete_event', as: "delete_event"

  get '/rating/:rating' => 'games#rating', as: "rating"

  get '/auth/github/callback', to: 'users#create'


end

app/models/game.rb
class Game < ApplicationRecord
    validates(:title, :presence => true)
    validates :title, uniqueness: {
        scope: %i[system_id],
        message: 'has already been added for this system'
    }

    validates(:content_rating, :presence => true)
    validates(:system_id, :presence => true)
    validates(:company_id, :presence => true)

    belongs_to :company 
    belongs_to :system

    has_many :events, dependent: :destroy
    has_many :user_games, dependent: :destroy
    has_many :users, through: :user_games 

    def average_rating 
        sum = 0
        self.user_games.each do |user_game|
            if user_game.star_rating != nil 
                sum += user_game.star_rating 
            end 
        end 
        sum / user_games.size 
    end 


    
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
    before_action :require_login
    
    def index 
        @games = Game.all 
    end 

    def new 
        @game = Game.new
        @systems = System.all
        @companies = Company.all
    end 

    def create 
        @game = Game.new(game_params)
        @system = System.find_by(id: @game.system_id)
        @game.company_id = @system.company_id
        if @game.valid? 
            @game.save 
            if params[:game][:user_game] == "true" 
                user_game = UserGame.create(user_id: current_user.id, game_id: @game.id)
                redirect_to game_path(@game)
            else 
                redirect_to game_path(@game)
            end
        else 
            render :new 
        end 
    end 
      
    def show 
        @game = Game.find(params[:id])
    end 

    def rating 
        @formatted = params[:rating].split("_").map{|element| element.capitalize}.join(" ")
        @games = Game.all.select{|game| game.content_rating == @formatted}
    end 


    private 

    def game_params
        params.require(:game).permit(:title, :content_rating, :system_id, :company_id)
    end 

    def require_login
        unless logged_in?
            flash[:error] = "You must be logged in to access this section"
            redirect_to login_path 
          end
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/index.html.erb
<h1> Games </h1>


<br>
<br>
<div class="switchdrop"> 
<button class="dropbtn_1">Nintendo Switch Games </button>

<div class="switch"><% @games.each do |game| %>
    <% if game.system.name == "Nintendo Switch" %>
        <%= link_to game.title, game_path(game) %> 
        <% end %>
    <% end %></div> </div>
<br>
<br>
<br>

<div class="three_dsdrop"> 
<button class="dropbtn_2">Nintendo 3DS Games </button>

<div class="three_ds"><% @games.each do |game| %>
    <% if game.system.name == "Nintendo 3DS" %>
        <%= link_to game.title, game_path(game) %> 
        <% end %>
    <% end %></div></div>
<br>
<br>

<div class="xbox_onedrop"> 
<button class="dropbtn_3">Xbox One Games </button>

<div class="xbox_one"><% @games.each do |game| %>
    <% if game.system.name == "Xbox One" %>
        <%= link_to game.title, game_path(game)%>
        <% end %>
    <% end %></div></div>
<br>
<br>
<div class="ps_fourdrop">
<button class="dropbtn_4"> Playstation 4 Games </button>

<div class="ps_four"><% @games.each do |game| %>
    <% if game.system.name == "Playstation 4" %>
        <%= link_to game.title, game_path(game) %>
        <% end %>
    <% end %></div></div>
    <br>
    <br>
   
    <h5><div class="create_game"><%= link_to "Add a Game to Vie Games", new_game_path %></h5></div>
    

app/views/games/new.html.erb
<% if @game.errors.any? %>
   <div id="error_explanation">
      <h2> 
         <%= pluralize(@game.errors.count, "error") %>
         prohibited this game from being saved:
      </h2>

      <ul> 
        <% @game.errors.full_messages.each do |msg| %>
            <li> <%= msg %> </li>
        <% end %>
     </ul>
    </div>
    <% end %>

<h1> Add a Game to Vie Games!</h1> 

<%= form_for(@game) do |f| %> 
    <h6><b>Title:</b></h6><%= f.text_field :title %> </br></br>
    <h6><b>Select Content Rating:</b></h6>
    Everyone: <%= f.radio_button(:content_rating, "Everyone")%>
    Everyone 10 & Up: <%= f.radio_button(:content_rating, "Everyone 10 & Up")%>
    Teen: <%= f.radio_button(:content_rating, "Teen")%>
    Mature: <%= f.radio_button(:content_rating, "Mature")%></br></br>
    <h6> <b>Select a System: </b></h6> 
    <%=f.collection_select(:system_id, System.all, :id, :name)%></br></br>
    <h6><b> Own This Game?</b></h6> 
    <label for="true"> True </label>
    <input type="radio" name="game[user_game]" value= true>
    <label for="false"> False </label>
    <input type="radio" name="game[user_game]" value= false></br></br>
    
    <%= f.submit :onclick => "return confirm('Please confirm details are correct. You cannot edit or delete a game once added to the database.')" %>
    <% end %>


app/views/games/rating.html.erb
<h1> <%= @formatted %> </h1>
<div class="rating"><% @games.each do |game| %>
    <h5><li><%= link_to game.title, game_path(game) %></li></h5>
    <div class="system"><%= link_to game.system.name, system_path(game.system)%></h6></div>
    <% end %> 
    <br>
   

app/views/games/show.html.erb
<h1><%= @game.title %> </h1>

<% rating = @game.content_rating.downcase.gsub(" ","_") %>
<h6> <b>Content Rating:</b></h6> <%= link_to @game.content_rating, rating_path(rating)%> </br>
<h6> <b>Game System:</b></h6> <%= link_to @game.system.name, system_path(@game.system) %></br>
<h6> <b>Company:</b></h6> <%= link_to @game.company.name, company_path(@game.company)%></br>
<h6> <b>Number of Users who play <%= @game.title %>:</b></h6> <%= @game.users.count %><br>
<% if @game.user_games.count > 0 %>
<h6> <b>Average User Rating:</b></h6> <%= @game.average_rating %>
<% end %> 


<% user_game = UserGame.find_by(game_id: @game.id, user_id: current_user.id) %>
<% if current_user.games.find{|game| game.id == @game.id} && user_game.star_rating == nil %>
    <%= form_for(:user_game, :url => add_rating_path, method: "patch") do |f| %>
        <h6> <b>Add a Rating for <%= @game.title %></b> </h6>
        1 <%= f.radio_button(:star_rating, 1)%>
        2 <%= f.radio_button(:star_rating, 2)%>
        3 <%= f.radio_button(:star_rating, 3) %>
        4 <%= f.radio_button(:star_rating, 4) %>
        5 <%= f.radio_button(:star_rating, 5) %></br></br>
        <%= f.submit "Add Rating" %>
    <% end %>
<% end %></br></br>

<% if !(current_user.games.find{|game| game.id == @game.id}) %>
    <div class="collect_game"><h6><%= link_to "Add #{@game.title} to Your Collection", add_game_path(@game) %> <br>
<% end %></h6></div><br><br>

<div class="upcoming_event"><h6><%= link_to "Upcoming Events for #{@game.title}", game_events_path(@game)%></h6></div> <br><br>

<% if current_user.games.find{|game| game.id == @game.id} %>
    <div class="create_event"><h6><%= link_to "Create an Event for #{@game.title}", new_game_event_path(@game)%></h6></div><br><br>

    <div class="collect_game"><h6><%= link_to "Remove #{@game.title} from Your Collection", delete_game_path(@game) %></h6></div><br>
<% end %>